/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Venta;

import ideosystem.Main;
import javax.swing.JOptionPane;

/**
 *
 * @author Renzo
 */
public class BuscarVenta extends javax.swing.JPanel {

    /**
     * Creates new form BuscarVenta
     */
    private Main ma;

    public BuscarVenta(Main ma) {
        initComponents();
        this.ma = ma;
        tabVentas.setModel(ma.ventas.GetAllFromVentas());
        btnAnular.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCriterio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVentas = new javax.swing.JTable();
        btnAnular = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("BUSCAR VENTA");

        jLabel2.setText("Nro Venta / Cliente");

        txtCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCriterioKeyReleased(evt);
            }
        });

        tabVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"000001", "Renzo Mazuelos", "13000", "2013-05-15", null}
            },
            new String [] {
                "Nro. Venta", "Cliente", "Total", "Fecha", "Estado"
            }
        ));
        tabVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabVentasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabVentas);

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/001-02-1.png"))); // NOI18N
        btnAnular.setText("Anular");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnular)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCriterioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioKeyReleased
        tabVentas.setModel(ma.ventas.GetVentaFromVentaByNombreClienteOrNroVenta(txtCriterio.getText()));
    }//GEN-LAST:event_txtCriterioKeyReleased

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "Esta segudo de anular la venta ?", "AVISO", JOptionPane.OK_OPTION);
        if (respuesta == 0) {
            int idventa = Integer.parseInt(tabVentas.getValueAt(tabVentas.getSelectedRow(), 0).toString());
            ma.ventas.AnularVenta(idventa);
            btnAnular.setEnabled(false);
            btnEliminar.setEnabled(false);
            tabVentas.setModel(ma.ventas.GetVentaFromVentaByNombreClienteOrNroVenta(txtCriterio.getText()));
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    private void tabVentasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVentasMouseReleased
        btnAnular.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tabVentasMouseReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "Esta segudo de ELIMINAR la venta ?", "AVISO", JOptionPane.OK_OPTION);
        if (respuesta == 0) {
            int idventa = Integer.parseInt(tabVentas.getValueAt(tabVentas.getSelectedRow(), 0).toString());
            ma.ventas.EliminarVenta(idventa);
            btnAnular.setEnabled(false);
            btnEliminar.setEnabled(false);
            ma.ventas.GetVentaFromVentaByNombreClienteOrNroVenta(txtCriterio.getText());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabVentas;
    private javax.swing.JTextField txtCriterio;
    // End of variables declaration//GEN-END:variables
}
