/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Adicionales;

import Entidades.Cliente;
import AccesoDatos.ClienteDAO;
import Venta.RealizarVenta;
import ideosystem.Main;
import java.awt.Color;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Renzo
 */
public class frmBuscarCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmBuscarCliente
     */
    private Main ma;
    private RealizarVenta venta;
    private Servicio.GenerarComprobante gcomprobante;
    private ClienteDAO clienteDAO;

    public frmBuscarCliente(Main ma, Servicio.GenerarComprobante gcomprobante) {
        initComponents();
        this.ma = ma;
        this.gcomprobante = gcomprobante;
        clienteDAO = new ClienteDAO(ma);

        tabCliente.setModel(clienteDAO.GetClientesByNombreRazonSocial(txtRazonSocial.getText()));

        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        //this.getContentPane().setBackground(Color.BLACK);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public frmBuscarCliente(Main ma, RealizarVenta venta) {
        initComponents();
        this.ma = ma;
        this.venta = venta;
        clienteDAO = new ClienteDAO(ma);
        tabCliente.setModel(clienteDAO.GetClientesByNombreRazonSocial(txtRazonSocial.getText()));

        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        //this.getContentPane().setBackground(Color.BLACK);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabCliente = new javax.swing.JTable();
        txtRazonSocial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUSCAR CLIENTE");

        btnAceptar.setText("Seleccionar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        tabCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Renzo Ricardo", "Mazuelos Loyaza"},
                {"Richard", "Aguilar Alvarez"},
                {"Claudio Severino", "PÃ©rez Bocanegra"}
            },
            new String [] {
                "Nombres", "Apellidos"
            }
        ));
        tabCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabCliente);

        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyReleased(evt);
            }
        });

        jLabel1.setText("Nombre o Apellidos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String camposCliente[] = clienteDAO.GetValuesClientesByNombreRazonSocial(tabCliente.getValueAt(tabCliente.getSelectedRow(), 0).toString());
        try {
            venta.SetValoresCliente(camposCliente[0], camposCliente[1], camposCliente[2]);
        } catch (Exception error) {
            gcomprobante.SetValoresCliente(camposCliente[0], camposCliente[1], camposCliente[2]);
        }
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void tabClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabClienteMouseClicked
        btnAceptar.setEnabled(true);
        String camposCliente[] = clienteDAO.GetValuesClientesByNombreRazonSocial(tabCliente.getValueAt(tabCliente.getSelectedRow(), 0).toString());
        if (evt.getClickCount() == 2) {
            try {
                venta.SetValoresCliente(camposCliente[0], camposCliente[1], camposCliente[2]);
            } catch (Exception error) {
                gcomprobante.SetValoresCliente(camposCliente[0], camposCliente[1], camposCliente[2]);
            }
            this.dispose();
        }
    }//GEN-LAST:event_tabClienteMouseClicked

    private void txtRazonSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyReleased
        tabCliente.setModel(clienteDAO.GetClientesByNombreRazonSocial(txtRazonSocial.getText()));
    }//GEN-LAST:event_txtRazonSocialKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabCliente;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
