/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Adicionales;

import Servicio.GenerarComprobante;
import Venta.RealizarVenta;
import ideosystem.Main;
import java.awt.Color;

/**
 *
 * @author Renzo
 */
public class frmBuscarProducto extends javax.swing.JFrame {

    /**
     * Creates new form frmBuscarProducto
     */
    private Main ma;
    private RealizarVenta venta;
    private GenerarComprobante gComprobante;
    private int opcion = 0;
    
    public frmBuscarProducto(){
//        initComponents();
//        this.ma = ma;
//        tabProducto.setModel(ma.productos.GetProductoByDescripcion(txtRazonSocial.getText()));
//        this.setVisible(true);
//        this.setResizable(false);
//        this.setLocationRelativeTo(null);
//        this.getContentPane().setBackground(Color.white);
//        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public frmBuscarProducto(Main ma, GenerarComprobante gComprobante) {
        initComponents();
        this.ma = ma;
        this.gComprobante = gComprobante;
        opcion = 1;
        tabProducto.setModel(ma.productos.GetProductosRepuestosByDescripcion(txtRazonSocial.getText()));

        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public frmBuscarProducto(Main ma, RealizarVenta venta) {
        initComponents();
        this.ma = ma;
        this.venta = venta;
        opcion = 2;
        tabProducto.setModel(ma.productos.GetProductoByDescripcion(txtRazonSocial.getText()));

        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRazonSocial = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUSCAR PRODUCTO");

        txtRazonSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRazonSocialKeyReleased(evt);
            }
        });

        btnAceptar.setText("Seleccionar");
        btnAceptar.setEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        tabProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Sony PlayStation 3"},
                {"Celular Nokia Lumia N900"},
                {"Celular Samsung Galaxy S3"}
            },
            new String [] {
                "DescripciÃ³n"
            }
        ));
        tabProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabProducto);

        jLabel1.setText("CÃ³digo o DescricpciÃ³n:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String camposProducto[] = ma.productos.GetValuesProductosByDescripcion(tabProducto.getValueAt(tabProducto.getSelectedRow(), 0).toString());
        venta.SetValoresProducto(camposProducto[0], camposProducto[1], camposProducto[2]);
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void tabProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProductoMouseClicked
        btnAceptar.setEnabled(true);
        String camposProducto[] = ma.productos.GetValuesProductosByDescripcion(tabProducto.getValueAt(tabProducto.getSelectedRow(), 0).toString());

        if (evt.getClickCount() == 2) {
            if (opcion == 0) {
                
            }else if (opcion == 1){
                gComprobante.SetValoresProducto(camposProducto[0], camposProducto[1], camposProducto[2]);
            }else if(opcion ==2){
                venta.SetValoresProducto(camposProducto[0], camposProducto[1], camposProducto[2]);
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_tabProductoMouseClicked

    private void txtRazonSocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonSocialKeyReleased
        if (opcion == 0) {
            
        }else if(opcion == 1){
            tabProducto.setModel(ma.productos.GetProductosRepuestosByDescripcion(txtRazonSocial.getText()));
        }else if(opcion == 2){
            tabProducto.setModel(ma.productos.GetProductoByDescripcion(txtRazonSocial.getText()));
        }
        
    }//GEN-LAST:event_txtRazonSocialKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabProducto;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
